
package qkf.sto.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import qkf.sto.service.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ExpressQuery", targetNamespace = "http://service.sto.qkf/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ExpressQuery {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryJsonByCode", targetNamespace = "http://service.sto.qkf/", className = "qkf.sto.service.QueryJsonByCode")
    @ResponseWrapper(localName = "queryJsonByCodeResponse", targetNamespace = "http://service.sto.qkf/", className = "qkf.sto.service.QueryJsonByCodeResponse")
    public String queryJsonByCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
