
package qkf.sto.service.impl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ExpressQueryImplService", targetNamespace = "http://impl.service.sto.qkf/", wsdlLocation = "http://localhost:8080/sto_query/expressQuery?wsdl")
public class ExpressQueryImplService
    extends Service
{

    private final static URL EXPRESSQUERYIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException EXPRESSQUERYIMPLSERVICE_EXCEPTION;
    private final static QName EXPRESSQUERYIMPLSERVICE_QNAME = new QName("http://impl.service.sto.qkf/", "ExpressQueryImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/sto_query/expressQuery?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EXPRESSQUERYIMPLSERVICE_WSDL_LOCATION = url;
        EXPRESSQUERYIMPLSERVICE_EXCEPTION = e;
    }

    public ExpressQueryImplService() {
        super(__getWsdlLocation(), EXPRESSQUERYIMPLSERVICE_QNAME);
    }

    public ExpressQueryImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), EXPRESSQUERYIMPLSERVICE_QNAME, features);
    }

    public ExpressQueryImplService(URL wsdlLocation) {
        super(wsdlLocation, EXPRESSQUERYIMPLSERVICE_QNAME);
    }

    public ExpressQueryImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EXPRESSQUERYIMPLSERVICE_QNAME, features);
    }

    public ExpressQueryImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ExpressQueryImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ExpressQuery
     */
    @WebEndpoint(name = "ExpressQueryImplPort")
    public ExpressQuery getExpressQueryImplPort() {
        return super.getPort(new QName("http://impl.service.sto.qkf/", "ExpressQueryImplPort"), ExpressQuery.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ExpressQuery
     */
    @WebEndpoint(name = "ExpressQueryImplPort")
    public ExpressQuery getExpressQueryImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.sto.qkf/", "ExpressQueryImplPort"), ExpressQuery.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EXPRESSQUERYIMPLSERVICE_EXCEPTION!= null) {
            throw EXPRESSQUERYIMPLSERVICE_EXCEPTION;
        }
        return EXPRESSQUERYIMPLSERVICE_WSDL_LOCATION;
    }

}
